version: "3.7"

services:
  readarr:
    container_name: readarr
    image: cr.hotio.dev/hotio/readarr
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/Media/docker/readarr/config:/config
      - /home/Media/docker/deluge/downloads:/downloads
      - /home/Media/Books:/Books
      - /home/Media/Books/Audiobooks:/Audiobooks